# Generated by Django 4.1.5 on 2023-01-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('item_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('item_name', models.CharField(default='', max_length=50)),
                ('user_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('user_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('user_age', models.IntegerField(default=0)),
                ('user_sex', models.CharField(default='', max_length=1)),
                ('user_last_location', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
